name: Daz test action
description: This is here to test GitHub actions in the marketplace

inputs:
  test-intput:
    description: Test input parameter
    required: false

outputs:
  test-output:
    description: Test action output

runs:
  using: "composite"
    steps:
      - name: Setup Gradle
        uses: gradle/gradle-build-action@main

branding:
  icon: 'box'
  color: 'gray-dark'
